/**
 * @fileoverview Procurement Plans TypeScript Type Definitions
 * @version Next.js 15.5.4 / TypeScript 5.7.2 / Prisma 6.17.1
 * @author Bagizi-ID Development Team
 * @see {@link /docs/PROCUREMENT_WORKFLOW_GUIDE.md} Procurement Documentation
 * 
 * TYPE SYSTEM ARCHITECTURE:
 * - Domain Types: Core business entities from Prisma
 * - Form Input Types: For React Hook Form (dates as strings)
 * - API Response Types: For API endpoints (dates as Date objects)
 * - Display Types: For UI components with formatted data
 * - Filter Types: For list filtering and search
 * 
 * NOTE: ProcurementPlan in Prisma doesn't have items (they're in Procurement model)
 * This is a budget planning entity, not a detailed item list
 */

import type { 
  ProcurementPlan,
  Procurement,
  InventoryCategory,
  SPPG,
  User,
  NutritionProgram,
} from '@prisma/client'
import type { LucideIcon } from 'lucide-react'

// ================================ ENUMS & CONSTANTS ================================

/**
 * Plan approval status (matches Prisma string field)
 */
export type PlanApprovalStatus =
  | 'DRAFT'
  | 'SUBMITTED'
  | 'UNDER_REVIEW'
  | 'APPROVED'
  | 'REJECTED'
  | 'CANCELLED'

/**
 * Plan type options
 */
export type PlanType = 'MONTHLY' | 'QUARTERLY' | 'ANNUAL' | 'SPECIAL'

/**
 * Budget category priorities
 */
export type BudgetCategory = 'PROTEIN' | 'CARB' | 'VEGETABLE' | 'FRUIT' | 'OTHER'

// ================================ DOMAIN TYPES (FROM PRISMA) ================================

/**
 * Complete Plan with all relations
 * Used in detail views and API responses
 */
export interface PlanWithRelations extends ProcurementPlan {
  sppg: Pick<SPPG, 'id' | 'name' | 'code'>
  program?: Pick<NutritionProgram, 'id' | 'name'> | null
  submittedByUser?: Pick<User, 'id' | 'name' | 'email'> | null
  approvedByUser?: Pick<User, 'id' | 'name' | 'email'> | null
  procurements?: Array<Pick<Procurement, 'id' | 'procurementCode' | 'status' | 'totalAmount'>>
}

/**
 * Plan list item (minimal data for tables)
 */
export interface PlanListItem {
  id: string
  planName: string
  planMonth: string
  planYear: number
  planQuarter: number | null
  approvalStatus: string
  totalBudget: number
  usedBudget: number
  remainingBudget: number
  targetRecipients: number
  targetMeals: number
  createdAt: Date
  updatedAt: Date
}

// ================================ FORM INPUT TYPES (STRINGS FOR DATES) ================================

/**
 * Budget allocation for different categories
 */
export interface BudgetAllocation {
  proteinBudget?: number
  carbBudget?: number
  vegetableBudget?: number
  fruitBudget?: number
  otherBudget?: number
}

/**
 * Form input for creating plans
 * Used with React Hook Form - no date fields (uses month/year)
 */
export interface CreatePlanFormInput {
  // Basic fields
  programId?: string
  planName: string
  planMonth: string // Format: "JANUARY", "FEBRUARY", etc or "2025-01"
  planYear: number
  planQuarter?: number // 1, 2, 3, 4
  
  // Menu Plan Integration (NEW)
  menuPlanId?: string
  menuBasedBudget?: number
  autoGeneratedItems?: Record<string, unknown> // JSON field
  
  // Budget fields
  totalBudget: number
  proteinBudget?: number
  carbBudget?: number
  vegetableBudget?: number
  fruitBudget?: number
  otherBudget?: number
  
  // Targets
  targetRecipients: number
  targetMeals: number
  costPerMeal?: number
  emergencyBuffer?: number
  
  // Approval workflow (NEW)
  submissionNotes?: string
  
  // General notes
  notes?: string
}

/**
 * Form input for updating plans
 * All fields optional for partial updates
 */
export type UpdatePlanFormInput = Partial<CreatePlanFormInput>

/**
 * Form input for plan filters
 */
export interface PlanFiltersFormInput {
  search?: string
  approvalStatus?: string[]
  planYear?: number
  planMonth?: string
  planQuarter?: number
  minBudget?: number
  maxBudget?: number
}

// ================================ API REQUEST/RESPONSE TYPES ================================

/**
 * API request for creating plans
 * No date conversion needed (uses month/year)
 */
export interface CreatePlanRequest {
  programId?: string
  planName: string
  planMonth: string
  planYear: number
  planQuarter?: number
  totalBudget: number
  proteinBudget?: number
  carbBudget?: number
  vegetableBudget?: number
  fruitBudget?: number
  otherBudget?: number
  targetRecipients: number
  targetMeals: number
  costPerMeal?: number
  emergencyBuffer?: number
  notes?: string
}

/**
 * API request for updating plans
 */
export type UpdatePlanRequest = Partial<CreatePlanRequest>

/**
 * API response for single plan
 */
export type PlanResponse = PlanWithRelations

/**
 * API response for plan list
 */
export interface PlanListResponse {
  plans: PlanListItem[]
  pagination: {
    page: number
    pageSize: number
    totalItems: number
    totalPages: number
  }
}

/**
 * API response for plan stats
 */
export interface PlanStatsResponse {
  overview: {
    totalPlans: number
    totalBudget: number
    allocatedBudget: number
    usedBudget: number
    remainingBudget: number
    averageBudget: number
    totalRecipients: number
    totalMeals: number
  }
  statusBreakdown: {
    draft: number
    submitted: number
    underReview: number
    approved: number
    rejected: number
    cancelled: number
    details: Array<{
      approvalStatus: string
      count: number
      totalBudget: number
    }>
  }
  budgetAllocation: {
    protein: number
    carb: number
    vegetable: number
    fruit: number
    other: number
    total: number
  }
  monthlyTrend: Array<{
    month: string
    year: number
    count: number
    totalBudget: number
  }>
  recentPlans: Array<{
    id: string
    planName: string
    planMonth: string
    planYear: number
    approvalStatus: string
    totalBudget: number
    usedBudget: number
  }>
}

// ================================ DISPLAY TYPES (FOR UI COMPONENTS) ================================

/**
 * Plan card display data
 * Used in list views and cards
 */
export interface PlanCardData {
  id: string
  planName: string
  planMonth: string
  planYear: number
  planQuarter: number | null
  approvalStatus: string
  statusLabel: string
  statusColor: string
  totalBudget: string // Formatted: "Rp 10,000,000"
  usedBudget: string // Formatted: "Rp 5,000,000"
  remainingBudget: string // Formatted: "Rp 5,000,000"
  budgetUsagePercent: number // 0-100
  targetRecipients: number
  targetMeals: number
  costPerMeal: string // Formatted: "Rp 8,500"
}

/**
 * Plan timeline event
 */
export interface PlanTimelineEvent {
  id: string
  type: 'CREATED' | 'UPDATED' | 'SUBMITTED' | 'APPROVED' | 'REJECTED' | 'CANCELLED'
  title: string
  description: string
  timestamp: Date
  timestampFormatted: string
  user?: {
    id: string
    name: string
    email: string
  }
  icon: string
  color: string
}

/**
 * Plan statistics card data
 */
export interface PlanStatsCardData {
  label: string
  value: string | number
  change?: number // Percentage change
  changeLabel?: string
  icon: string
  color: string
  trend?: 'up' | 'down' | 'neutral'
}

// ================================ FILTER & SEARCH TYPES ================================

/**
 * Plan filters for API queries
 */
export interface PlanFilters {
  search?: string
  approvalStatus?: PlanApprovalStatus[]
  planYear?: number
  planMonth?: string
  planQuarter?: number
  minBudget?: number
  maxBudget?: number
  page?: number
  pageSize?: number
  sortBy?: 'planName' | 'planMonth' | 'planYear' | 'totalBudget' | 'usedBudget' | 'createdAt'
  sortOrder?: 'asc' | 'desc'
}

/**
 * Plan sort options
 */
export type PlanSortOption = {
  value: string
  label: string
  field: 'planName' | 'planMonth' | 'planYear' | 'totalBudget' | 'usedBudget' | 'createdAt'
  order: 'asc' | 'desc'
}

// ================================ SUBMISSION & APPROVAL TYPES ================================

/**
 * Submit plan for review
 */
export interface PlanSubmissionInput {
  submissionNotes?: string
}

// ================================ ACTION TYPES ================================

/**
 * Submit plan for approval
 */
export interface PlanSubmissionInput {
  planId: string
  submissionNotes?: string
}

/**
 * Approve plan
 */
export interface PlanApprovalInput {
  planId: string
  approvalNotes?: string
}

/**
 * Reject plan
 */
export interface PlanRejectionInput {
  planId: string
  rejectionReason: string
}

/**
 * Cancel plan
 */
export interface PlanCancellationInput {
  planId: string
  cancellationReason: string
}

// ================================ UTILITY TYPES ================================

/**
 * Plan status info with UI metadata
 */
export interface PlanStatusInfo {
  status: PlanApprovalStatus
  label: string
  color: string
  bgColor: string
  icon: LucideIcon
  description: string
}

/**
 * Budget utilization info
 */
export interface BudgetUtilization {
  total: number
  allocated: number
  used: number
  remaining: number
  percentageUsed: number
  percentageAllocated: number
  status: 'UNDER_BUDGET' | 'ON_BUDGET' | 'OVER_BUDGET' | 'EXCEEDED'
  statusColor: string
  statusLabel: string
}

/**
 * Budget category breakdown
 */
export interface BudgetCategoryBreakdown {
  category: BudgetCategory
  amount: number
  percentage: number
  label: string
  color: string
}

// ================================ EXPORT ALL TYPES ================================

export type {
  ProcurementPlan,
  Procurement,
  InventoryCategory,
}
