/**
 * @fileoverview Plan Items List Component
 * @version Next.js 15.5.4 / shadcn/ui
 * @author Bagizi-ID Development Team
 * 
 * BUSINESS WORKFLOW: PROCUREMENT PLANNING
 * ========================================
 * 
 * 1. PERENCANAAN KEBUTUHAN
 *    - Analisis menu yang akan diproduksi
 *    - Hitung estimasi kebutuhan bahan per kategori
 *    - Generate daftar belanja dengan quantities
 * 
 * 2. BUDGETING
 *    - Estimasi harga per item berdasarkan market price
 *    - Alokasi budget ke kategori (Protein 40%, Carb 30%, dll)
 *    - Validasi budget vs total estimated cost
 * 
 * 3. SUPPLIER SELECTION
 *    - Suggest suppliers berdasarkan item category
 *    - Multiple supplier options untuk comparison
 *    - Track supplier performance history
 * 
 * 4. PRIORITIZATION
 *    - HIGH: Items critical untuk menu utama
 *    - MEDIUM: Items untuk variety/alternates
 *    - LOW: Items optional/nice-to-have
 * 
 * 5. PROCUREMENT EXECUTION
 *    - Convert planned items → Purchase Orders
 *    - Track order status per item
 *    - Monitor delivery & quality
 */

'use client'

import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Separator } from '@/components/ui/separator'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import {
  ShoppingCart,
  Package,
  AlertCircle,
  CheckCircle2,
  Info,
  ShoppingBag,
  DollarSign,
  Truck,
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { formatCurrency, formatNumber } from '../utils'

// ================================ TYPES ================================

interface PlanItem {
  category: string
  itemName: string
  estimatedQuantity: number
  unit: string
  estimatedPrice: number
  estimatedTotal: number
  budgetCategory: string
  priority?: 'HIGH' | 'MEDIUM' | 'LOW'
  notes?: string
  suggestedSuppliers?: string[]
}

interface AutoGeneratedItems {
  items: PlanItem[]
  totalEstimatedCost: number
  generatedAt: string
  basedOnMenu?: boolean
  isDraft?: boolean
  needsReview?: boolean
  reviewNotes?: string
  summary?: {
    totalItems: number
    proteinItems?: number
    carbItems?: number
    vegetableItems?: number
    fruitItems?: number
    otherItems?: number
    highPriorityItems?: number
    mediumPriorityItems?: number
    lowPriorityItems?: number
    luxuryItems?: number
    seasonalPricing?: boolean
    estimatedPriceIncrease?: string
  }
}

interface PlanItemsListProps {
  autoGeneratedItems: AutoGeneratedItems | null
  planStatus: string
  planId: string
  className?: string
}

// ================================ HELPERS ================================

function getCategoryIcon(category: string) {
  switch (category) {
    case 'PROTEIN':
      return <Package className="h-4 w-4 text-blue-600" />
    case 'KARBOHIDRAT':
      return <Package className="h-4 w-4 text-green-600" />
    case 'SAYURAN':
      return <Package className="h-4 w-4 text-emerald-600" />
    case 'BUAH':
      return <Package className="h-4 w-4 text-orange-600" />
    case 'BUMBU_REMPAH':
      return <Package className="h-4 w-4 text-yellow-600" />
    case 'SUSU_OLAHAN':
      return <Package className="h-4 w-4 text-purple-600" />
    default:
      return <Package className="h-4 w-4 text-gray-600" />
  }
}

function getCategoryBadgeColor(category: string): string {
  switch (category) {
    case 'PROTEIN':
      return 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400'
    case 'KARBOHIDRAT':
      return 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400'
    case 'SAYURAN':
      return 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400'
    case 'BUAH':
      return 'bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400'
    case 'BUMBU_REMPAH':
      return 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400'
    case 'SUSU_OLAHAN':
      return 'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400'
    default:
      return 'bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-400'
  }
}

function getPriorityBadgeColor(priority: string): string {
  switch (priority) {
    case 'HIGH':
      return 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400'
    case 'MEDIUM':
      return 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400'
    case 'LOW':
      return 'bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-400'
    default:
      return 'bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-400'
  }
}

function formatCategoryLabel(category: string): string {
  const labels: Record<string, string> = {
    PROTEIN: 'Protein',
    KARBOHIDRAT: 'Karbohidrat',
    SAYURAN: 'Sayuran',
    BUAH: 'Buah',
    BUMBU_REMPAH: 'Bumbu & Rempah',
    SUSU_OLAHAN: 'Susu & Olahan',
  }
  return labels[category] || category
}

// ================================ COMPONENT ================================

export function PlanItemsList({
  autoGeneratedItems,
  planStatus,
  className,
}: PlanItemsListProps) {
  const [expandedCategories, setExpandedCategories] = useState<Set<string>>(new Set(['PROTEIN']))

  // If no items
  if (!autoGeneratedItems || !autoGeneratedItems.items || autoGeneratedItems.items.length === 0) {
    return (
      <Card className={className}>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <ShoppingCart className="h-5 w-5 text-primary" />
            Daftar Barang yang Akan Dibeli
          </CardTitle>
          <CardDescription>
            Rencana pengadaan bahan berdasarkan menu dan kebutuhan produksi
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex flex-col items-center justify-center py-8 text-center">
            <ShoppingBag className="h-16 w-16 text-muted-foreground/50 mb-4" />
            <h3 className="text-lg font-semibold text-foreground mb-2">
              Belum Ada Daftar Barang
            </h3>
            <p className="text-sm text-muted-foreground max-w-md mb-4">
              Daftar barang belanja akan di-generate otomatis berdasarkan menu yang direncanakan.
              Klik tombol di bawah untuk generate daftar belanja.
            </p>
            <Button variant="outline">
              <ShoppingCart className="mr-2 h-4 w-4" />
              Generate Daftar Belanja
            </Button>
          </div>
        </CardContent>
      </Card>
    )
  }

  const { items, totalEstimatedCost, summary, needsReview, reviewNotes } = autoGeneratedItems

  // Group items by category
  const itemsByCategory = items.reduce((acc, item) => {
    if (!acc[item.category]) {
      acc[item.category] = []
    }
    acc[item.category].push(item)
    return acc
  }, {} as Record<string, PlanItem[]>)

  const categories = Object.keys(itemsByCategory).sort()

  const toggleCategory = (category: string) => {
    const newExpanded = new Set(expandedCategories)
    if (newExpanded.has(category)) {
      newExpanded.delete(category)
    } else {
      newExpanded.add(category)
    }
    setExpandedCategories(newExpanded)
  }

  return (
    <Card className={className}>
      <CardHeader>
        <div className="flex items-start justify-between">
          <div className="space-y-2">
            <CardTitle className="flex items-center gap-2">
              <ShoppingCart className="h-5 w-5 text-primary" />
              Daftar Barang yang Akan Dibeli
            </CardTitle>
            <CardDescription>
              {summary?.totalItems || items.length} item • Est. Total: {formatCurrency(totalEstimatedCost)}
            </CardDescription>
          </div>
          
          {planStatus === 'DRAFT' && (
            <Button variant="outline" size="sm">
              <ShoppingCart className="mr-2 h-4 w-4" />
              Edit Daftar
            </Button>
          )}
        </div>

        {/* Workflow Info Banner */}
        <div className="mt-4 rounded-lg border border-blue-200 bg-blue-50 p-4 dark:border-blue-800 dark:bg-blue-950/30">
          <div className="flex gap-3">
            <Info className="h-5 w-5 text-blue-600 flex-shrink-0 mt-0.5" />
            <div className="space-y-2 text-sm">
              <p className="font-semibold text-blue-900 dark:text-blue-100">
                📋 Business Workflow: Procurement Planning
              </p>
              <ol className="list-decimal list-inside space-y-1 text-blue-800 dark:text-blue-200">
                <li><strong>Perencanaan:</strong> Analisis menu → Generate daftar kebutuhan</li>
                <li><strong>Budgeting:</strong> Estimasi harga → Validasi budget</li>
                <li><strong>Supplier Selection:</strong> Pilih supplier per kategori</li>
                <li><strong>Prioritization:</strong> HIGH (critical) → MEDIUM → LOW</li>
                <li><strong>Execution:</strong> Convert ke Purchase Orders → Track delivery</li>
              </ol>
            </div>
          </div>
        </div>

        {/* Review Warning (if needed) */}
        {needsReview && reviewNotes && (
          <div className="mt-4 rounded-lg border border-yellow-200 bg-yellow-50 p-4 dark:border-yellow-800 dark:bg-yellow-950/30">
            <div className="flex gap-3">
              <AlertCircle className="h-5 w-5 text-yellow-600 flex-shrink-0 mt-0.5" />
              <div className="space-y-1 text-sm">
                <p className="font-semibold text-yellow-900 dark:text-yellow-100">
                  Perlu Review
                </p>
                <p className="text-yellow-800 dark:text-yellow-200">
                  {reviewNotes}
                </p>
              </div>
            </div>
          </div>
        )}
      </CardHeader>

      <CardContent className="space-y-6">
        {/* Summary Stats */}
        {summary && (
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 p-4 rounded-lg bg-muted">
            <div className="text-center">
              <div className="text-2xl font-bold text-foreground">{summary.totalItems}</div>
              <div className="text-xs text-muted-foreground">Total Items</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-red-600">{summary.highPriorityItems || 0}</div>
              <div className="text-xs text-muted-foreground">High Priority</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-yellow-600">{summary.mediumPriorityItems || 0}</div>
              <div className="text-xs text-muted-foreground">Medium Priority</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-blue-600">{formatCurrency(totalEstimatedCost)}</div>
              <div className="text-xs text-muted-foreground">Est. Total Cost</div>
            </div>
          </div>
        )}

        <Separator />

        {/* Items by Category */}
        <div className="space-y-4">
          {categories.map((category) => {
            const categoryItems = itemsByCategory[category]
            const isExpanded = expandedCategories.has(category)
            const categoryTotal = categoryItems.reduce((sum, item) => sum + item.estimatedTotal, 0)

            return (
              <div key={category} className="border rounded-lg overflow-hidden">
                {/* Category Header */}
                <button
                  onClick={() => toggleCategory(category)}
                  className="w-full flex items-center justify-between p-4 bg-muted hover:bg-muted/80 transition-colors"
                >
                  <div className="flex items-center gap-3">
                    {getCategoryIcon(category)}
                    <div className="text-left">
                      <div className="flex items-center gap-2">
                        <span className="font-semibold text-foreground">
                          {formatCategoryLabel(category)}
                        </span>
                        <Badge variant="secondary" className={getCategoryBadgeColor(category)}>
                          {categoryItems.length} items
                        </Badge>
                      </div>
                      <div className="text-sm text-muted-foreground mt-0.5">
                        Total: {formatCurrency(categoryTotal)}
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge variant="outline" className="text-xs">
                      {isExpanded ? '▼' : '▶'}
                    </Badge>
                  </div>
                </button>

                {/* Category Items Table */}
                {isExpanded && (
                  <div className="border-t">
                    <Table>
                      <TableHeader>
                        <TableRow>
                          <TableHead>Nama Barang</TableHead>
                          <TableHead className="text-center">Qty</TableHead>
                          <TableHead className="text-center">Unit</TableHead>
                          <TableHead className="text-right">Harga</TableHead>
                          <TableHead className="text-right">Total</TableHead>
                          <TableHead className="text-center">Priority</TableHead>
                          <TableHead>Supplier</TableHead>
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        {categoryItems.map((item, idx) => (
                          <TableRow key={idx}>
                            <TableCell>
                              <div>
                                <div className="font-medium">{item.itemName}</div>
                                {item.notes && (
                                  <div className="text-xs text-muted-foreground mt-1">
                                    {item.notes}
                                  </div>
                                )}
                              </div>
                            </TableCell>
                            <TableCell className="text-center font-semibold">
                              {formatNumber(item.estimatedQuantity)}
                            </TableCell>
                            <TableCell className="text-center">
                              <Badge variant="outline" className="text-xs">
                                {item.unit}
                              </Badge>
                            </TableCell>
                            <TableCell className="text-right text-sm">
                              {formatCurrency(item.estimatedPrice)}
                            </TableCell>
                            <TableCell className="text-right font-semibold">
                              {formatCurrency(item.estimatedTotal)}
                            </TableCell>
                            <TableCell className="text-center">
                              {item.priority && (
                                <Badge 
                                  variant="secondary" 
                                  className={cn('text-xs', getPriorityBadgeColor(item.priority))}
                                >
                                  {item.priority}
                                </Badge>
                              )}
                            </TableCell>
                            <TableCell>
                              {item.suggestedSuppliers && item.suggestedSuppliers.length > 0 && (
                                <div className="text-xs text-muted-foreground">
                                  <Truck className="inline h-3 w-3 mr-1" />
                                  {item.suggestedSuppliers[0]}
                                  {item.suggestedSuppliers.length > 1 && (
                                    <span className="ml-1">+{item.suggestedSuppliers.length - 1}</span>
                                  )}
                                </div>
                              )}
                            </TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  </div>
                )}
              </div>
            )
          })}
        </div>

        <Separator />

        {/* Total Summary */}
        <div className="flex items-center justify-between p-4 rounded-lg bg-primary/5 border border-primary/20">
          <div className="flex items-center gap-2">
            <DollarSign className="h-5 w-5 text-primary" />
            <span className="font-semibold text-foreground">Total Estimasi Biaya</span>
          </div>
          <span className="text-xl font-bold text-primary">
            {formatCurrency(totalEstimatedCost)}
          </span>
        </div>

        {/* Next Steps */}
        {planStatus === 'APPROVED' && (
          <div className="rounded-lg border border-green-200 bg-green-50 p-4 dark:border-green-800 dark:bg-green-950/30">
            <div className="flex gap-3">
              <CheckCircle2 className="h-5 w-5 text-green-600 flex-shrink-0 mt-0.5" />
              <div className="space-y-2 text-sm">
                <p className="font-semibold text-green-900 dark:text-green-100">
                  ✅ Langkah Selanjutnya
                </p>
                <p className="text-green-800 dark:text-green-200">
                  Plan sudah APPROVED. Anda dapat mulai membuat Purchase Orders untuk items di atas.
                </p>
                <Button size="sm" className="mt-2">
                  <ShoppingCart className="mr-2 h-4 w-4" />
                  Buat Purchase Order
                </Button>
              </div>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
