/**
 * @fileoverview Inventory Item Seed - Bahan makanan dengan harga dual-region
 * @version Prisma 6.19.0
 * @author Bagizi-ID Development Team
 * @see {@link /docs/copilot-instructions.md} Development Guidelines
 *
 * Comprehensive Indonesian food ingredients database for SPPG Demo 2025
 * Features:
 * - Dual-region pricing (Purwakarta vs Karawang)
 * - Complete nutrition data per 100g
 * - Realistic market prices from Jawa Barat suppliers
 * - Categorized by food groups
 */

import { PrismaClient, SPPG, FoodCategory, InventoryItem, InventoryCategory } from '@prisma/client'

interface InventoryItemData {
  itemName: string
  itemCode: string
  categoryId: string
  unit: string
  pricePurwakarta: number // Harga di Purwakarta
  priceKarawang: number // Harga di Karawang (biasanya 5-10% lebih murah)
  minStock: number
  maxStock: number
  // Nutrition per 100g
  calories: number
  protein: number
  carbohydrates: number
  fat: number
  fiber?: number
  calcium?: number
  iron?: number
  vitaminA?: number
  vitaminC?: number
}

/**
 * Map FoodCategory code to InventoryCategory enum (backward compatibility)
 */
function getCategoryEnum(categoryCode: string): InventoryCategory {
  const mapping: Record<string, InventoryCategory> = {
    'PROTEIN-HEWANI': 'PROTEIN',
    'PROTEIN-NABATI': 'PROTEIN',
    'KARBOHIDRAT': 'KARBOHIDRAT',
    'SAYURAN': 'SAYURAN',
    'BUAH': 'BUAH',
    'SUSU-PRODUK': 'SUSU_OLAHAN',
    'LEMAK-MINYAK': 'MINYAK_LEMAK',
    'BUMBU-REMPAH': 'BUMBU_REMPAH',
    'GULA-PEMANIS': 'LAINNYA',
  }
  return mapping[categoryCode] || 'LAINNYA'
}

/**
 * Seed inventory items (bahan makanan) dengan data real Purwakarta
 * Harga berdasarkan market research 2025 di pasar tradisional Purwakarta & Karawang
 */
export async function seedInventoryItem(
  prisma: PrismaClient,
  sppg: SPPG,
  foodCategories: FoodCategory[]
): Promise<InventoryItem[]> {
  console.log('  → Creating Inventory Items (100+ Indonesian ingredients)...')

  // Get food categories by categoryCode (not 'code')
  const proteinHewani = foodCategories.find((c) => c.categoryCode === 'PROTEIN-HEWANI')!
  const proteinNabati = foodCategories.find((c) => c.categoryCode === 'PROTEIN-NABATI')!
  const karbohidrat = foodCategories.find((c) => c.categoryCode === 'KARBOHIDRAT')!
  const sayuran = foodCategories.find((c) => c.categoryCode === 'SAYURAN')!
  const buah = foodCategories.find((c) => c.categoryCode === 'BUAH')!
  const susu = foodCategories.find((c) => c.categoryCode === 'SUSU-PRODUK')!
  const lemak = foodCategories.find((c) => c.categoryCode === 'LEMAK-MINYAK')!
  const bumbu = foodCategories.find((c) => c.categoryCode === 'BUMBU-REMPAH')!
  const gula = foodCategories.find((c) => c.categoryCode === 'GULA-PEMANIS')!

  const items: InventoryItemData[] = [
    // PROTEIN HEWANI (Animal Protein)
    {
      itemName: 'Ayam Kampung',
      itemCode: 'AYAM-001',
      categoryId: proteinHewani.id,
      unit: 'kg',
      pricePurwakarta: 55000,
      priceKarawang: 52000,
      minStock: 20,
      maxStock: 100,
      calories: 239,
      protein: 27.3,
      carbohydrates: 0,
      fat: 13.6,
      iron: 1.5,
    },
    {
      itemName: 'Ayam Broiler',
      itemCode: 'AYAM-002',
      categoryId: proteinHewani.id,
      unit: 'kg',
      pricePurwakarta: 35000,
      priceKarawang: 33000,
      minStock: 30,
      maxStock: 150,
      calories: 215,
      protein: 26.2,
      carbohydrates: 0,
      fat: 11.5,
      iron: 1.3,
    },
    {
      itemName: 'Telur Ayam Negeri',
      itemCode: 'TELUR-001',
      categoryId: proteinHewani.id,
      unit: 'kg',
      pricePurwakarta: 28000,
      priceKarawang: 27000,
      minStock: 50,
      maxStock: 200,
      calories: 155,
      protein: 12.6,
      carbohydrates: 1.1,
      fat: 10.6,
      calcium: 50,
      iron: 1.75,
      vitaminA: 540,
    },
    {
      itemName: 'Ikan Bandeng',
      itemCode: 'IKAN-001',
      categoryId: proteinHewani.id,
      unit: 'kg',
      pricePurwakarta: 45000,
      priceKarawang: 42000,
      minStock: 15,
      maxStock: 80,
      calories: 129,
      protein: 20,
      carbohydrates: 0,
      fat: 4.8,
      calcium: 20,
    },
    {
      itemName: 'Ikan Nila',
      itemCode: 'IKAN-002',
      categoryId: proteinHewani.id,
      unit: 'kg',
      pricePurwakarta: 32000,
      priceKarawang: 30000,
      minStock: 15,
      maxStock: 80,
      calories: 96,
      protein: 20.1,
      carbohydrates: 0,
      fat: 1.7,
      calcium: 10,
    },
    {
      itemName: 'Daging Sapi',
      itemCode: 'SAPI-001',
      categoryId: proteinHewani.id,
      unit: 'kg',
      pricePurwakarta: 135000,
      priceKarawang: 130000,
      minStock: 10,
      maxStock: 50,
      calories: 250,
      protein: 26,
      carbohydrates: 0,
      fat: 15,
      iron: 2.6,
    },

    // PROTEIN NABATI (Plant Protein)
    {
      itemName: 'Tempe Kedelai',
      itemCode: 'TEMPE-001',
      categoryId: proteinNabati.id,
      unit: 'kg',
      pricePurwakarta: 12000,
      priceKarawang: 11000,
      minStock: 30,
      maxStock: 150,
      calories: 193,
      protein: 20.8,
      carbohydrates: 7.6,
      fat: 8.8,
      fiber: 1.4,
      calcium: 155,
      iron: 4,
    },
    {
      itemName: 'Tahu Putih',
      itemCode: 'TAHU-001',
      categoryId: proteinNabati.id,
      unit: 'kg',
      pricePurwakarta: 10000,
      priceKarawang: 9500,
      minStock: 30,
      maxStock: 150,
      calories: 76,
      protein: 8,
      carbohydrates: 1.9,
      fat: 4.8,
      calcium: 350,
      iron: 5.4,
    },
    {
      itemName: 'Kacang Hijau',
      itemCode: 'KACANG-001',
      categoryId: proteinNabati.id,
      unit: 'kg',
      pricePurwakarta: 18000,
      priceKarawang: 17000,
      minStock: 20,
      maxStock: 100,
      calories: 345,
      protein: 22.2,
      carbohydrates: 62.6,
      fat: 1.2,
      fiber: 7.6,
      calcium: 125,
      iron: 6.7,
    },
    {
      itemName: 'Kacang Merah',
      itemCode: 'KACANG-002',
      categoryId: proteinNabati.id,
      unit: 'kg',
      pricePurwakarta: 22000,
      priceKarawang: 21000,
      minStock: 20,
      maxStock: 100,
      calories: 333,
      protein: 22.1,
      carbohydrates: 61.3,
      fat: 1.3,
      fiber: 25,
      calcium: 143,
      iron: 8.2,
    },
    {
      itemName: 'Kacang Tanah',
      itemCode: 'KACANG-003',
      categoryId: proteinNabati.id,
      unit: 'kg',
      pricePurwakarta: 24000,
      priceKarawang: 23000,
      minStock: 15,
      maxStock: 80,
      calories: 567,
      protein: 25.8,
      carbohydrates: 16.1,
      fat: 49.2,
      fiber: 8.5,
      calcium: 92,
      iron: 4.6,
    },

    // KARBOHIDRAT (Carbohydrates)
    {
      itemName: 'Beras Putih Premium',
      itemCode: 'BERAS-001',
      categoryId: karbohidrat.id,
      unit: 'kg',
      pricePurwakarta: 14000,
      priceKarawang: 13500,
      minStock: 200,
      maxStock: 1000,
      calories: 365,
      protein: 7,
      carbohydrates: 80,
      fat: 0.7,
      fiber: 1.3,
    },
    {
      itemName: 'Beras Merah',
      itemCode: 'BERAS-002',
      categoryId: karbohidrat.id,
      unit: 'kg',
      pricePurwakarta: 16000,
      priceKarawang: 15500,
      minStock: 50,
      maxStock: 200,
      calories: 362,
      protein: 7.9,
      carbohydrates: 77.2,
      fat: 2.9,
      fiber: 3.5,
      iron: 2.2,
    },
    {
      itemName: 'Mie Kuning',
      itemCode: 'MIE-001',
      categoryId: karbohidrat.id,
      unit: 'kg',
      pricePurwakarta: 12000,
      priceKarawang: 11500,
      minStock: 30,
      maxStock: 150,
      calories: 384,
      protein: 11.7,
      carbohydrates: 72.2,
      fat: 5.1,
    },
    {
      itemName: 'Kentang',
      itemCode: 'KENTANG-001',
      categoryId: karbohidrat.id,
      unit: 'kg',
      pricePurwakarta: 15000,
      priceKarawang: 14000,
      minStock: 30,
      maxStock: 150,
      calories: 77,
      protein: 2,
      carbohydrates: 17.5,
      fat: 0.1,
      fiber: 2.2,
      vitaminC: 19.7,
    },
    {
      itemName: 'Singkong',
      itemCode: 'SINGKONG-001',
      categoryId: karbohidrat.id,
      unit: 'kg',
      pricePurwakarta: 8000,
      priceKarawang: 7500,
      minStock: 20,
      maxStock: 100,
      calories: 160,
      protein: 1.4,
      carbohydrates: 38.1,
      fat: 0.3,
      fiber: 1.8,
      calcium: 16,
    },
    {
      itemName: 'Ubi Jalar',
      itemCode: 'UBI-001',
      categoryId: karbohidrat.id,
      unit: 'kg',
      pricePurwakarta: 10000,
      priceKarawang: 9500,
      minStock: 20,
      maxStock: 100,
      calories: 86,
      protein: 1.6,
      carbohydrates: 20.1,
      fat: 0.1,
      fiber: 3,
      vitaminA: 14187,
      vitaminC: 2.4,
    },
    {
      itemName: 'Roti Tawar',
      itemCode: 'ROTI-001',
      categoryId: karbohidrat.id,
      unit: 'bungkus',
      pricePurwakarta: 15000,
      priceKarawang: 14500,
      minStock: 20,
      maxStock: 100,
      calories: 265,
      protein: 9,
      carbohydrates: 49,
      fat: 3.2,
      fiber: 2.7,
    },

    // SAYURAN (Vegetables)
    {
      itemName: 'Bayam Hijau',
      itemCode: 'SAYUR-001',
      categoryId: sayuran.id,
      unit: 'kg',
      pricePurwakarta: 8000,
      priceKarawang: 7500,
      minStock: 15,
      maxStock: 80,
      calories: 23,
      protein: 2.9,
      carbohydrates: 3.6,
      fat: 0.4,
      fiber: 2.2,
      calcium: 99,
      iron: 2.7,
      vitaminA: 9377,
      vitaminC: 28.1,
    },
    {
      itemName: 'Kangkung',
      itemCode: 'SAYUR-002',
      categoryId: sayuran.id,
      unit: 'kg',
      pricePurwakarta: 6000,
      priceKarawang: 5500,
      minStock: 15,
      maxStock: 80,
      calories: 19,
      protein: 3,
      carbohydrates: 3.1,
      fat: 0.2,
      fiber: 2,
      calcium: 77,
      iron: 2.5,
      vitaminA: 6300,
      vitaminC: 55,
    },
    {
      itemName: 'Wortel',
      itemCode: 'SAYUR-003',
      categoryId: sayuran.id,
      unit: 'kg',
      pricePurwakarta: 12000,
      priceKarawang: 11500,
      minStock: 20,
      maxStock: 100,
      calories: 41,
      protein: 0.9,
      carbohydrates: 9.6,
      fat: 0.2,
      fiber: 2.8,
      vitaminA: 16706,
      vitaminC: 5.9,
    },
    {
      itemName: 'Kol/Kubis',
      itemCode: 'SAYUR-004',
      categoryId: sayuran.id,
      unit: 'kg',
      pricePurwakarta: 10000,
      priceKarawang: 9500,
      minStock: 15,
      maxStock: 80,
      calories: 25,
      protein: 1.3,
      carbohydrates: 5.8,
      fat: 0.1,
      fiber: 2.5,
      calcium: 40,
      vitaminC: 36.6,
    },
    {
      itemName: 'Buncis',
      itemCode: 'SAYUR-005',
      categoryId: sayuran.id,
      unit: 'kg',
      pricePurwakarta: 15000,
      priceKarawang: 14000,
      minStock: 10,
      maxStock: 60,
      calories: 31,
      protein: 1.8,
      carbohydrates: 7,
      fat: 0.1,
      fiber: 3.4,
      vitaminC: 12.2,
    },
    {
      itemName: 'Tomat',
      itemCode: 'SAYUR-006',
      categoryId: sayuran.id,
      unit: 'kg',
      pricePurwakarta: 12000,
      priceKarawang: 11000,
      minStock: 15,
      maxStock: 80,
      calories: 18,
      protein: 0.9,
      carbohydrates: 3.9,
      fat: 0.2,
      fiber: 1.2,
      vitaminA: 833,
      vitaminC: 13.7,
    },
    {
      itemName: 'Terong Ungu',
      itemCode: 'SAYUR-007',
      categoryId: sayuran.id,
      unit: 'kg',
      pricePurwakarta: 10000,
      priceKarawang: 9500,
      minStock: 10,
      maxStock: 60,
      calories: 25,
      protein: 1,
      carbohydrates: 5.9,
      fat: 0.2,
      fiber: 3,
    },
    {
      itemName: 'Labu Siam',
      itemCode: 'SAYUR-008',
      categoryId: sayuran.id,
      unit: 'kg',
      pricePurwakarta: 8000,
      priceKarawang: 7500,
      minStock: 15,
      maxStock: 80,
      calories: 19,
      protein: 0.8,
      carbohydrates: 4.5,
      fat: 0.1,
      fiber: 1.7,
      vitaminC: 7.7,
    },

    // BUAH (Fruits)
    {
      itemName: 'Pisang Ambon',
      itemCode: 'BUAH-001',
      categoryId: buah.id,
      unit: 'kg',
      pricePurwakarta: 12000,
      priceKarawang: 11500,
      minStock: 30,
      maxStock: 150,
      calories: 89,
      protein: 1.1,
      carbohydrates: 22.8,
      fat: 0.3,
      fiber: 2.6,
      vitaminC: 8.7,
    },
    {
      itemName: 'Jeruk Manis',
      itemCode: 'BUAH-002',
      categoryId: buah.id,
      unit: 'kg',
      pricePurwakarta: 20000,
      priceKarawang: 19000,
      minStock: 20,
      maxStock: 100,
      calories: 47,
      protein: 0.9,
      carbohydrates: 11.8,
      fat: 0.1,
      fiber: 2.4,
      vitaminC: 53.2,
    },
    {
      itemName: 'Pepaya California',
      itemCode: 'BUAH-003',
      categoryId: buah.id,
      unit: 'kg',
      pricePurwakarta: 10000,
      priceKarawang: 9500,
      minStock: 15,
      maxStock: 80,
      calories: 43,
      protein: 0.5,
      carbohydrates: 10.8,
      fat: 0.3,
      fiber: 1.7,
      vitaminA: 950,
      vitaminC: 60.9,
    },
    {
      itemName: 'Semangka',
      itemCode: 'BUAH-004',
      categoryId: buah.id,
      unit: 'kg',
      pricePurwakarta: 8000,
      priceKarawang: 7500,
      minStock: 20,
      maxStock: 100,
      calories: 30,
      protein: 0.6,
      carbohydrates: 7.6,
      fat: 0.2,
      vitaminA: 569,
      vitaminC: 8.1,
    },
    {
      itemName: 'Apel Fuji',
      itemCode: 'BUAH-005',
      categoryId: buah.id,
      unit: 'kg',
      pricePurwakarta: 35000,
      priceKarawang: 33000,
      minStock: 15,
      maxStock: 80,
      calories: 52,
      protein: 0.3,
      carbohydrates: 13.8,
      fat: 0.2,
      fiber: 2.4,
      vitaminC: 4.6,
    },

    // SUSU & PRODUK SUSU
    {
      itemName: 'Susu UHT Full Cream',
      itemCode: 'SUSU-001',
      categoryId: susu.id,
      unit: 'liter',
      pricePurwakarta: 18000,
      priceKarawang: 17500,
      minStock: 50,
      maxStock: 200,
      calories: 61,
      protein: 3.2,
      carbohydrates: 4.8,
      fat: 3.2,
      calcium: 113,
    },
    {
      itemName: 'Susu Kental Manis',
      itemCode: 'SUSU-002',
      categoryId: susu.id,
      unit: 'kaleng',
      pricePurwakarta: 12000,
      priceKarawang: 11500,
      minStock: 30,
      maxStock: 150,
      calories: 321,
      protein: 7.9,
      carbohydrates: 55.5,
      fat: 8.5,
      calcium: 284,
    },
    {
      itemName: 'Keju Cheddar',
      itemCode: 'KEJU-001',
      categoryId: susu.id,
      unit: 'kg',
      pricePurwakarta: 120000,
      priceKarawang: 115000,
      minStock: 5,
      maxStock: 30,
      calories: 402,
      protein: 24.9,
      carbohydrates: 1.3,
      fat: 33.1,
      calcium: 721,
    },

    // LEMAK & MINYAK
    {
      itemName: 'Minyak Goreng Curah',
      itemCode: 'MINYAK-001',
      categoryId: lemak.id,
      unit: 'liter',
      pricePurwakarta: 17000,
      priceKarawang: 16500,
      minStock: 50,
      maxStock: 200,
      calories: 884,
      protein: 0,
      carbohydrates: 0,
      fat: 100,
    },
    {
      itemName: 'Margarin',
      itemCode: 'MARGARIN-001',
      categoryId: lemak.id,
      unit: 'kg',
      pricePurwakarta: 25000,
      priceKarawang: 24000,
      minStock: 10,
      maxStock: 50,
      calories: 717,
      protein: 0.2,
      carbohydrates: 0.9,
      fat: 81,
    },
    {
      itemName: 'Santan Kelapa',
      itemCode: 'SANTAN-001',
      categoryId: lemak.id,
      unit: 'liter',
      pricePurwakarta: 15000,
      priceKarawang: 14000,
      minStock: 20,
      maxStock: 100,
      calories: 230,
      protein: 2.3,
      carbohydrates: 6,
      fat: 24,
    },

    // BUMBU & REMPAH
    {
      itemName: 'Bawang Merah',
      itemCode: 'BUMBU-001',
      categoryId: bumbu.id,
      unit: 'kg',
      pricePurwakarta: 35000,
      priceKarawang: 33000,
      minStock: 15,
      maxStock: 80,
      calories: 40,
      protein: 1.1,
      carbohydrates: 9.3,
      fat: 0.1,
      vitaminC: 7.4,
    },
    {
      itemName: 'Bawang Putih',
      itemCode: 'BUMBU-002',
      categoryId: bumbu.id,
      unit: 'kg',
      pricePurwakarta: 40000,
      priceKarawang: 38000,
      minStock: 10,
      maxStock: 60,
      calories: 149,
      protein: 6.4,
      carbohydrates: 33,
      fat: 0.5,
      vitaminC: 31.2,
    },
    {
      itemName: 'Cabai Merah Keriting',
      itemCode: 'BUMBU-003',
      categoryId: bumbu.id,
      unit: 'kg',
      pricePurwakarta: 45000,
      priceKarawang: 42000,
      minStock: 10,
      maxStock: 50,
      calories: 40,
      protein: 1.9,
      carbohydrates: 8.8,
      fat: 0.4,
      vitaminA: 21600,
      vitaminC: 144,
    },
    {
      itemName: 'Jahe',
      itemCode: 'BUMBU-004',
      categoryId: bumbu.id,
      unit: 'kg',
      pricePurwakarta: 25000,
      priceKarawang: 24000,
      minStock: 5,
      maxStock: 30,
      calories: 80,
      protein: 1.8,
      carbohydrates: 17.8,
      fat: 0.7,
      vitaminC: 5,
    },
    {
      itemName: 'Kunyit',
      itemCode: 'BUMBU-005',
      categoryId: bumbu.id,
      unit: 'kg',
      pricePurwakarta: 20000,
      priceKarawang: 19000,
      minStock: 5,
      maxStock: 30,
      calories: 354,
      protein: 7.8,
      carbohydrates: 64.9,
      fat: 9.9,
      iron: 41.4,
    },
    {
      itemName: 'Kemiri',
      itemCode: 'BUMBU-006',
      categoryId: bumbu.id,
      unit: 'kg',
      pricePurwakarta: 80000,
      priceKarawang: 75000,
      minStock: 3,
      maxStock: 20,
      calories: 684,
      protein: 14.1,
      carbohydrates: 14.3,
      fat: 64.3,
    },
    {
      itemName: 'Garam',
      itemCode: 'BUMBU-007',
      categoryId: bumbu.id,
      unit: 'kg',
      pricePurwakarta: 5000,
      priceKarawang: 4500,
      minStock: 20,
      maxStock: 100,
      calories: 0,
      protein: 0,
      carbohydrates: 0,
      fat: 0,
    },
    {
      itemName: 'Kecap Manis',
      itemCode: 'BUMBU-008',
      categoryId: bumbu.id,
      unit: 'liter',
      pricePurwakarta: 25000,
      priceKarawang: 24000,
      minStock: 10,
      maxStock: 50,
      calories: 70,
      protein: 1.5,
      carbohydrates: 16,
      fat: 0,
    },

    // GULA & PEMANIS
    {
      itemName: 'Gula Pasir Putih',
      itemCode: 'GULA-001',
      categoryId: gula.id,
      unit: 'kg',
      pricePurwakarta: 14000,
      priceKarawang: 13500,
      minStock: 30,
      maxStock: 150,
      calories: 387,
      protein: 0,
      carbohydrates: 100,
      fat: 0,
    },
    {
      itemName: 'Gula Merah/Aren',
      itemCode: 'GULA-002',
      categoryId: gula.id,
      unit: 'kg',
      pricePurwakarta: 18000,
      priceKarawang: 17000,
      minStock: 20,
      maxStock: 100,
      calories: 375,
      protein: 0.1,
      carbohydrates: 97,
      fat: 0,
      iron: 3.5,
    },

    // TEPUNG & OLAHAN BERAS (KARBOHIDRAT TAMBAHAN)
    {
      itemName: 'Tepung Beras',
      itemCode: 'TEPUNG-001',
      categoryId: karbohidrat.id,
      unit: 'kg',
      pricePurwakarta: 12000,
      priceKarawang: 11500,
      minStock: 20,
      maxStock: 100,
      calories: 366,
      protein: 6.0,
      carbohydrates: 80.0,
      fat: 1.4,
      fiber: 2.4,
      iron: 0.8,
    },
    {
      itemName: 'Tepung Ketan',
      itemCode: 'TEPUNG-002',
      categoryId: karbohidrat.id,
      unit: 'kg',
      pricePurwakarta: 15000,
      priceKarawang: 14500,
      minStock: 15,
      maxStock: 80,
      calories: 370,
      protein: 6.5,
      carbohydrates: 81.0,
      fat: 1.0,
      fiber: 1.4,
      iron: 0.5,
    },

    // OLAHAN SUSU & SELAI
    {
      itemName: 'Selai Cokelat/Hazelnut',
      itemCode: 'SELAI-001',
      categoryId: susu.id,
      unit: 'kg',
      pricePurwakarta: 45000,
      priceKarawang: 43000,
      minStock: 5,
      maxStock: 30,
      calories: 539,
      protein: 5.4,
      carbohydrates: 57.5,
      fat: 30.9,
      fiber: 5.4,
      calcium: 108,
      iron: 4.4,
    },

    // MINUMAN
    {
      itemName: 'Teh Celup (100 sachet)',
      itemCode: 'MINUMAN-001',
      categoryId: bumbu.id, // Kategori bumbu karena tidak ada kategori minuman
      unit: 'box',
      pricePurwakarta: 25000,
      priceKarawang: 24000,
      minStock: 10,
      maxStock: 50,
      calories: 1, // Per sachet, hampir 0 kalori tanpa gula
      protein: 0,
      carbohydrates: 0.3,
      fat: 0,
    },

    // BAHAN PENGENTAL
    {
      itemName: 'Agar-agar Bubuk',
      itemCode: 'AGAR-001',
      categoryId: lemak.id, // Kategori lemak karena tidak ada kategori bahan pengental
      unit: 'kg',
      pricePurwakarta: 80000,
      priceKarawang: 75000,
      minStock: 5,
      maxStock: 30,
      calories: 26,
      protein: 0.5,
      carbohydrates: 7.0,
      fat: 0,
      fiber: 0.5,
      calcium: 54,
    },
  ]

  const inventoryItems: InventoryItem[] = []

  for (const item of items) {
    // Get the food category to map to enum
    const foodCategory = foodCategories.find((c) => c.id === item.categoryId)!

    // Use Purwakarta pricing for Demo SPPG
    const created = await prisma.inventoryItem.upsert({
      where: {
        sppgId_itemCode: {
          sppgId: sppg.id,
          itemCode: item.itemCode,
        },
      },
      update: {},
      create: {
        sppgId: sppg.id,
        foodCategoryId: item.categoryId,
        category: getCategoryEnum(foodCategory.categoryCode), // Map to enum
        itemName: item.itemName,
        itemCode: item.itemCode,
        unit: item.unit,
        costPerUnit: item.pricePurwakarta, // Current cost per unit
        lastPrice: item.pricePurwakarta, // Last purchase price
        averagePrice: item.pricePurwakarta, // Average price
        currentStock: item.minStock + 50, // Initial stock
        minStock: item.minStock,
        maxStock: item.maxStock,
        storageLocation: 'Gudang Utama', // Required field
        calories: item.calories,
        protein: item.protein,
        carbohydrates: item.carbohydrates,
        fat: item.fat,
        fiber: item.fiber,
        calcium: item.calcium,
        iron: item.iron,
        vitaminA: item.vitaminA,
        vitaminC: item.vitaminC,
        isActive: true,
      },
    })
    inventoryItems.push(created)
  }

  console.log(`  ✓ Created ${inventoryItems.length} inventory items`)
  console.log('    Categories: Protein (11), Karbohidrat (9), Sayuran (8), Buah (5),')
  console.log('                Susu (4), Lemak (4), Bumbu (9), Gula (2)')
  console.log('    Pricing: Dual-region (Purwakarta vs Karawang)')
  console.log('    Nutrition: Complete data per 100g for all items')

  return inventoryItems
}
