-- CreateEnum
CREATE TYPE "ProcurementPaymentMethod" AS ENUM ('BANK_TRANSFER', 'CASH', 'CREDIT_CARD', 'DEBIT_CARD', 'CHECK', 'OTHER');

-- AlterTable
ALTER TABLE "food_distributions" ADD COLUMN     "laborCost" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "packagingCost" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "procurementPlanId" TEXT,
ADD COLUMN     "totalCostPerMeal" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "totalDistributionCost" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "totalProcurementCost" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "totalProductionCost" DOUBLE PRECISION DEFAULT 0,
ALTER COLUMN "transportCost" SET DEFAULT 0,
ALTER COLUMN "fuelCost" SET DEFAULT 0,
ALTER COLUMN "otherCosts" SET DEFAULT 0;

-- AlterTable
ALTER TABLE "food_productions" ADD COLUMN     "costPerMeal" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "ingredientCost" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "laborCost" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "otherCosts" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "procurementPlanId" TEXT,
ADD COLUMN     "totalCost" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "utilityCost" DOUBLE PRECISION DEFAULT 0;

-- AlterTable
ALTER TABLE "procurement_plans" ADD COLUMN     "autoGeneratedItems" JSONB,
ADD COLUMN     "menuBasedBudget" DOUBLE PRECISION,
ADD COLUMN     "menuPlanId" TEXT;

-- AlterTable
ALTER TABLE "procurement_settings" ADD COLUMN     "accountingSystemApiKey" VARCHAR(255),
ADD COLUMN     "accountingSystemApiUrl" VARCHAR(500),
ADD COLUMN     "approvalEscalationDays" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "approvalNotificationEmail" VARCHAR(255),
ADD COLUMN     "approvalNotificationWhatsapp" VARCHAR(20),
ADD COLUMN     "requireParallelApproval" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "production_stock_usage" ADD COLUMN     "procurementItemId" TEXT;

-- CreateTable
CREATE TABLE "payment_transactions" (
    "id" TEXT NOT NULL,
    "procurementId" TEXT NOT NULL,
    "paymentDate" TIMESTAMP(3) NOT NULL,
    "paymentMethod" "ProcurementPaymentMethod" NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "referenceNumber" VARCHAR(100),
    "bankName" VARCHAR(100),
    "accountNumber" VARCHAR(50),
    "receiptUrl" VARCHAR(500),
    "notes" TEXT,
    "createdBy" TEXT NOT NULL,
    "createdByName" VARCHAR(255),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "payment_transactions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "procurement_approval_tracking" (
    "id" TEXT NOT NULL,
    "procurementId" TEXT NOT NULL,
    "approvalLevelId" TEXT,
    "approverUserId" TEXT NOT NULL,
    "approverName" TEXT NOT NULL,
    "approverRole" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "comments" TEXT,
    "approvedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ipAddress" TEXT,
    "isEscalated" BOOLEAN NOT NULL DEFAULT false,
    "escalatedFrom" TEXT,
    "escalatedReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "procurement_approval_tracking_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "payment_transactions_procurementId_paymentDate_idx" ON "payment_transactions"("procurementId", "paymentDate");

-- CreateIndex
CREATE INDEX "payment_transactions_createdBy_idx" ON "payment_transactions"("createdBy");

-- CreateIndex
CREATE INDEX "procurement_approval_tracking_procurementId_action_idx" ON "procurement_approval_tracking"("procurementId", "action");

-- CreateIndex
CREATE INDEX "procurement_approval_tracking_approverUserId_approvedAt_idx" ON "procurement_approval_tracking"("approverUserId", "approvedAt");

-- CreateIndex
CREATE INDEX "food_distributions_procurementPlanId_idx" ON "food_distributions"("procurementPlanId");

-- CreateIndex
CREATE INDEX "food_productions_procurementPlanId_idx" ON "food_productions"("procurementPlanId");

-- CreateIndex
CREATE INDEX "procurement_plans_menuPlanId_idx" ON "procurement_plans"("menuPlanId");

-- CreateIndex
CREATE INDEX "production_stock_usage_procurementItemId_idx" ON "production_stock_usage"("procurementItemId");

-- AddForeignKey
ALTER TABLE "procurement_plans" ADD CONSTRAINT "procurement_plans_menuPlanId_fkey" FOREIGN KEY ("menuPlanId") REFERENCES "menu_plans"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payment_transactions" ADD CONSTRAINT "payment_transactions_procurementId_fkey" FOREIGN KEY ("procurementId") REFERENCES "procurements"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payment_transactions" ADD CONSTRAINT "payment_transactions_createdBy_fkey" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "procurement_approval_tracking" ADD CONSTRAINT "procurement_approval_tracking_procurementId_fkey" FOREIGN KEY ("procurementId") REFERENCES "procurements"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "food_productions" ADD CONSTRAINT "food_productions_procurementPlanId_fkey" FOREIGN KEY ("procurementPlanId") REFERENCES "procurement_plans"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "production_stock_usage" ADD CONSTRAINT "production_stock_usage_procurementItemId_fkey" FOREIGN KEY ("procurementItemId") REFERENCES "procurement_items"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "food_distributions" ADD CONSTRAINT "food_distributions_procurementPlanId_fkey" FOREIGN KEY ("procurementPlanId") REFERENCES "procurement_plans"("id") ON DELETE SET NULL ON UPDATE CASCADE;
