/**
 * @fileoverview Procurement Plans Zod Validation Schemas
 * @version Next.js 15.5.4 / Zod 3.24.1
 * @author Bagizi-ID Development Team
 * @see {@link /docs/PROCUREMENT_WORKFLOW_GUIDE.md} Procurement Documentation
 * 
 * VALIDATION ARCHITECTURE:
 * - Form Schemas: For React Hook Form (no date transforms)
 * - API Schemas: For server-side validation
 * - Dual Type System: Forms use strings, API uses proper types
 * - NO TRANSFORMS in form schemas (breaks React Hook Form)
 * 
 * CRITICAL: ProcurementPlan uses month/year, NOT date ranges
 */

import { z } from 'zod'

// ================================ SHARED VALIDATION RULES ================================

/**
 * Plan name validation
 */
const planNameValidation = z
  .string()
  .min(5, 'Nama rencana minimal 5 karakter')
  .max(200, 'Nama rencana maksimal 200 karakter')
  .regex(/^[a-zA-Z0-9\s\-\/]+$/, 'Nama rencana hanya boleh mengandung huruf, angka, spasi, dan dash')

/**
 * Month validation (accepts "01"-"12", "JANUARY" or "2025-01" format)
 */
const planMonthValidation = z
  .string()
  .min(1, 'Bulan perencanaan harus diisi')
  .refine(
    (val) => {
      // Accept numeric month (01-12)
      const numericMonthRegex = /^(0[1-9]|1[0-2])$/
      if (numericMonthRegex.test(val)) return true
      
      // Accept month name (JANUARY, FEBRUARY, etc)
      const monthNames = [
        'JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE',
        'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER'
      ]
      if (monthNames.includes(val.toUpperCase())) return true
      
      // Accept YYYY-MM format
      const yearMonthRegex = /^\d{4}-(0[1-9]|1[0-2])$/
      return yearMonthRegex.test(val)
    },
    { message: 'Format bulan tidak valid (gunakan 01-12, nama bulan, atau YYYY-MM)' }
  )

/**
 * Year validation
 */
const planYearValidation = z
  .number()
  .int('Tahun harus berupa bilangan bulat')
  .min(2024, 'Tahun minimal 2024')
  .max(2030, 'Tahun maksimal 2030')

/**
 * Quarter validation
 */
const planQuarterValidation = z
  .number()
  .int('Kuartal harus berupa bilangan bulat')
  .min(1, 'Kuartal minimal 1')
  .max(4, 'Kuartal maksimal 4')
  .optional()

/**
 * Budget validation
 */
const budgetValidation = z
  .number()
  .positive('Anggaran harus lebih dari 0')
  .finite('Anggaran harus berupa angka yang valid')
  .max(10_000_000_000, 'Anggaran maksimal 10 miliar')

/**
 * Target recipients validation
 */
const targetRecipientsValidation = z
  .number()
  .int('Jumlah penerima harus berupa bilangan bulat')
  .positive('Jumlah penerima harus lebih dari 0')
  .max(100_000, 'Jumlah penerima maksimal 100.000')

/**
 * Target meals validation
 */
const targetMealsValidation = z
  .number()
  .int('Target makanan harus berupa bilangan bulat')
  .positive('Target makanan harus lebih dari 0')
  .max(10_000_000, 'Target makanan maksimal 10 juta')

// ================================ FORM SCHEMAS (NO TRANSFORMS) ================================

/**
 * Budget allocation schema for form
 */
export const budgetAllocationFormSchema = z.object({
  proteinBudget: budgetValidation.optional(),
  carbBudget: budgetValidation.optional(),
  vegetableBudget: budgetValidation.optional(),
  fruitBudget: budgetValidation.optional(),
  otherBudget: budgetValidation.optional(),
}).refine(
  (data) => {
    const total = (data.proteinBudget || 0) + 
                  (data.carbBudget || 0) + 
                  (data.vegetableBudget || 0) + 
                  (data.fruitBudget || 0) + 
                  (data.otherBudget || 0)
    return total >= 0
  },
  { message: 'Total alokasi anggaran tidak boleh negatif' }
)

/**
 * Create plan form schema
 * For React Hook Form - NO transforms
 */
export const createPlanFormSchema = z.object({
  // Basic fields
  programId: z.string().cuid('ID program tidak valid').optional(),
  planName: planNameValidation,
  planMonth: planMonthValidation,
  planYear: planYearValidation,
  planQuarter: planQuarterValidation,
  
  // Menu Plan Integration (NEW)
  menuPlanId: z.string().cuid('ID menu plan tidak valid').optional(),
  menuBasedBudget: budgetValidation.optional(),
  autoGeneratedItems: z.any().optional(), // JSON field
  
  // Budget fields
  totalBudget: budgetValidation,
  proteinBudget: budgetValidation.optional(),
  carbBudget: budgetValidation.optional(),
  vegetableBudget: budgetValidation.optional(),
  fruitBudget: budgetValidation.optional(),
  otherBudget: budgetValidation.optional(),
  
  // Targets
  targetRecipients: targetRecipientsValidation,
  targetMeals: targetMealsValidation,
  costPerMeal: z.number().positive('Biaya per makanan harus lebih dari 0').optional(),
  emergencyBuffer: z.number().min(0, 'Buffer darurat minimal 0').max(100, 'Buffer darurat maksimal 100%').optional(),
  
  // Approval workflow fields (NEW)
  submissionNotes: z.string().max(1000, 'Catatan pengajuan maksimal 1000 karakter').optional(),
  
  // General notes
  notes: z.string().max(1000, 'Catatan maksimal 1000 karakter').optional(),
}).refine(
  (data) => {
    // Validate budget allocation doesn't exceed total
    const allocatedBudget = (data.proteinBudget || 0) + 
                            (data.carbBudget || 0) + 
                            (data.vegetableBudget || 0) + 
                            (data.fruitBudget || 0) + 
                            (data.otherBudget || 0)
    return allocatedBudget <= data.totalBudget
  },
  {
    message: 'Total alokasi anggaran tidak boleh melebihi total anggaran',
    path: ['totalBudget'],
  }
).refine(
  (data) => {
    // Validate cost per meal matches budget and meals
    if (data.costPerMeal && data.targetMeals && data.totalBudget) {
      const calculatedBudget = data.costPerMeal * data.targetMeals
      const difference = Math.abs(calculatedBudget - data.totalBudget)
      const tolerance = data.totalBudget * 0.05 // 5% tolerance
      return difference <= tolerance
    }
    return true
  },
  {
    message: 'Biaya per makanan tidak sesuai dengan total anggaran dan target makanan',
    path: ['costPerMeal'],
  }
)

/**
 * Update plan form schema
 * Partial version of create schema
 */
export const updatePlanFormSchema = createPlanFormSchema.partial()

/**
 * Plan filters form schema
 */
export const planFiltersFormSchema = z.object({
  search: z.string().optional(),
  approvalStatus: z.array(z.string()).optional(),
  planYear: planYearValidation.optional(),
  planMonth: z.string().optional(),
  planQuarter: planQuarterValidation.optional(),
  minBudget: z.number().positive().optional(),
  maxBudget: z.number().positive().optional(),
}).refine(
  (data) => {
    if (data.minBudget && data.maxBudget) {
      return data.minBudget <= data.maxBudget
    }
    return true
  },
  {
    message: 'Anggaran minimum tidak boleh lebih dari anggaran maksimum',
    path: ['maxBudget'],
  }
)

// ================================ API REQUEST SCHEMAS ================================

/**
 * Create plan API request schema
 * For server-side validation
 */
export const createPlanAPISchema = z.object({
  programId: z.string().cuid().optional(),
  planName: planNameValidation,
  planMonth: planMonthValidation,
  planYear: planYearValidation,
  planQuarter: planQuarterValidation,
  totalBudget: budgetValidation,
  proteinBudget: budgetValidation.optional(),
  carbBudget: budgetValidation.optional(),
  vegetableBudget: budgetValidation.optional(),
  fruitBudget: budgetValidation.optional(),
  otherBudget: budgetValidation.optional(),
  targetRecipients: targetRecipientsValidation,
  targetMeals: targetMealsValidation,
  costPerMeal: z.number().positive().optional(),
  emergencyBuffer: z.number().min(0).max(100).optional(),
  notes: z.string().max(1000).optional(),
  // Menu plan integration fields
  menuPlanId: z.string().cuid('ID menu plan tidak valid').optional(),
  menuBasedBudget: budgetValidation.optional(),
  autoGeneratedItems: z.record(z.string(), z.unknown()).optional(),
  submissionNotes: z.string().max(1000).optional(),
})

/**
 * Update plan API request schema
 */
export const updatePlanAPISchema = createPlanAPISchema.extend({
  approvalStatus: z.enum([
    'DRAFT',
    'SUBMITTED',
    'UNDER_REVIEW',
    'APPROVED',
    'REJECTED',
    'CANCELLED'
  ]).optional(),
}).partial()

/**
 * Plan filters API schema
 */
export const planFiltersAPISchema = z.object({
  search: z.string().optional(),
  approvalStatus: z.array(z.enum([
    'DRAFT',
    'SUBMITTED',
    'UNDER_REVIEW',
    'APPROVED',
    'REJECTED',
    'CANCELLED'
  ])).optional(),
  planYear: planYearValidation.optional(),
  planMonth: z.string().optional(),
  planQuarter: planQuarterValidation.optional(),
  minBudget: z.number().positive().optional(),
  maxBudget: z.number().positive().optional(),
  programId: z.string().optional(), // Filter by nutrition program
  page: z.number().int().positive().default(1),
  limit: z.number().int().positive().max(100).default(10), // Alias for pageSize
  pageSize: z.number().int().positive().max(100).optional(), // Legacy support
  sortBy: z.enum(['planName', 'planMonth', 'planYear', 'totalBudget', 'usedBudget', 'createdAt']).default('createdAt'),
  sortOrder: z.enum(['asc', 'desc']).default('desc'),
})

// ================================ ACTION SCHEMAS (NEW) ================================

/**
 * Submit plan schema
 */
export const submitPlanSchema = z.object({
  planId: z.string().cuid('ID plan tidak valid'),
  submissionNotes: z.string().max(1000, 'Catatan pengajuan maksimal 1000 karakter').optional(),
})

/**
 * Approve plan schema
 */
export const approvePlanSchema = z.object({
  planId: z.string().cuid('ID plan tidak valid'),
  approvalNotes: z.string().max(1000, 'Catatan approval maksimal 1000 karakter').optional(),
})

/**
 * Reject plan schema
 */
export const rejectPlanSchema = z.object({
  planId: z.string().cuid('ID plan tidak valid'),
  rejectionReason: z.string().min(10, 'Alasan penolakan minimal 10 karakter').max(1000, 'Alasan penolakan maksimal 1000 karakter'),
})

/**
 * Cancel plan schema
 */
export const cancelPlanSchema = z.object({
  planId: z.string().cuid('ID plan tidak valid'),
  cancellationReason: z.string().min(10, 'Alasan pembatalan minimal 10 karakter').max(1000, 'Alasan pembatalan maksimal 1000 karakter'),
})

// ================================ TYPE INFERENCE ================================

export type CreatePlanFormInput = z.infer<typeof createPlanFormSchema>
export type UpdatePlanFormInput = z.infer<typeof updatePlanFormSchema>
export type PlanFiltersFormInput = z.infer<typeof planFiltersFormSchema>
export type SubmitPlanInput = z.infer<typeof submitPlanSchema>
export type ApprovePlanInput = z.infer<typeof approvePlanSchema>
export type RejectPlanInput = z.infer<typeof rejectPlanSchema>
export type CancelPlanInput = z.infer<typeof cancelPlanSchema>
export type CreatePlanAPIInput = z.infer<typeof createPlanAPISchema>
export type UpdatePlanAPIInput = z.infer<typeof updatePlanAPISchema>
export type PlanFiltersAPIInput = z.infer<typeof planFiltersAPISchema>
