/**
 * @fileoverview Procurement Plan Detail Page
 * @version Next.js 15.5.4 / App Router
 * @author Bagizi-ID Development Team
 * @route /procurement/plans/[id]
 * 
 * MODULAR ARCHITECTURE:
 * - Thin wrapper page using feature components
 * - Server-side data fetching with auth
 * - Multi-tenant isolation (sppgId filtering)
 * - SEO optimization with dynamic metadata
 */

import { Metadata } from 'next'
import { notFound, redirect } from 'next/navigation'
import { auth } from '@/auth'
import { db } from '@/lib/prisma'
import { canManageProcurement } from '@/lib/permissions'
import { ProcurementPageHeader } from '@/components/shared/procurement'
import { ArrowLeft, Edit, ClipboardList, Factory } from 'lucide-react'
import { 
  PlanDetail, 
  PlanActionsWrapper, 
  PlanRelatedRecords,
  PlanItemsList 
} from '@/features/sppg/procurement/plans/components'

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> {
  const { id } = await params
  const session = await auth()
  if (!session?.user?.sppgId) {
    return { title: 'Rencana Pengadaan | Bagizi-ID' }
  }

  const plan = await db.procurementPlan.findFirst({
    where: {
      id,
      sppgId: session.user.sppgId,
    },
    select: {
      planName: true,
    },
  })

  return {
    title: plan ? `${plan.planName} | Bagizi-ID` : 'Rencana Pengadaan | Bagizi-ID',
    description: 'Detail rencana pengadaan dan budget planning',
  }
}

/**
 * Procurement Plan Detail Page
 */
export default async function ProcurementPlanDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  
  // Auth check
  const session = await auth()
  if (!session?.user) {
    redirect('/login')
  }

  // Permission check
  if (!session.user.userRole || !canManageProcurement(session.user.userRole)) {
    redirect('/dashboard')
  }

  // Multi-tenant check
  if (!session.user.sppgId) {
    redirect('/dashboard')
  }

  // Fetch plan with multi-tenant isolation and related records
  const plan = await db.procurementPlan.findFirst({
    where: {
      id,
      sppgId: session.user.sppgId,
    },
    include: {
      sppg: {
        select: {
          id: true,
          code: true,
          name: true,
        },
      },
      program: {
        select: {
          id: true,
          name: true,
        },
      },
      // Phase 4: Fetch related productions
      productions: {
        select: {
          id: true,
          productionDate: true,
          batchNumber: true,
          plannedPortions: true,
          actualPortions: true,
          status: true,
          totalCost: true,
          menu: {
            select: {
              id: true,
              menuName: true,
              mealType: true,
            },
          },
        },
        orderBy: {
          productionDate: 'desc',
        },
      },
      // Phase 4: Fetch related distributions (via productions)
      // Note: We'll get this through productions since distributions link to productions
    },
  })

  if (!plan) {
    notFound()
  }

  const canEdit = plan.approvalStatus === 'DRAFT' || plan.approvalStatus === 'REVISION'
  const canCreateProduction = plan.approvalStatus === 'APPROVED'

  return (
    <div className="container mx-auto py-6 space-y-6">
      <ProcurementPageHeader
        title={plan.planName}
        description="Detail rencana pengadaan dan budget planning"
        icon={ClipboardList}
        breadcrumbs={['Procurement', 'Plans', plan.planName]}
        action={[
          {
            label: 'Kembali',
            href: '/procurement/plans',
            icon: ArrowLeft,
            variant: 'outline'
          },
          ...(canEdit ? [{
            label: 'Edit',
            href: `/procurement/plans/${plan.id}/edit`,
            icon: Edit,
            variant: 'default' as const
          }] : []),
          ...(canCreateProduction ? [{
            label: 'Buat Produksi',
            href: `/production/new/from-plan/${plan.id}`,
            icon: Factory,
            variant: 'default' as const
          }] : [])
        ]}
      />

      {/* Plan Actions - Enterprise-grade workflow buttons */}
      <PlanActionsWrapper 
        planId={plan.id} 
        currentStatus={plan.approvalStatus}
      />

      {/* Plan Detail with all sections */}
      <PlanDetail plan={plan} />

      {/* Phase 3: Auto-Generated Items List (Purchase List) */}
      <PlanItemsList 
        planId={plan.id}
        autoGeneratedItems={plan.autoGeneratedItems ? JSON.parse(JSON.stringify(plan.autoGeneratedItems)) : null}
        planStatus={plan.approvalStatus}
        className="mt-6"
      />

      {/* Phase 4: Related Productions Display */}
      <PlanRelatedRecords 
        productions={plan.productions}
        planId={plan.id}
      />
    </div>
  )
}
